// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="my_module,hls_ip_2018_2,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100tcsg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.470000,HLS_SYN_LAT=10,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=3,HLS_SYN_FF=508,HLS_SYN_LUT=448,HLS_VERSION=2018_2}" *)

module my_module (
        clk,
        reset,
        e_dout,
        e_empty_n,
        e_read,
        s_din,
        s_full_n,
        s_write
);


input   clk;
input   reset;
input  [31:0] e_dout;
input   e_empty_n;
output   e_read;
output  [31:0] s_din;
input   s_full_n;
output   s_write;

wire    grp_my_module_do_action_fu_56_e_read;
wire   [31:0] grp_my_module_do_action_fu_56_s_din;
wire    grp_my_module_do_action_fu_56_s_write;

my_module_do_action grp_my_module_do_action_fu_56(
    .ap_clk(clk),
    .ap_rst(reset),
    .e_dout(e_dout),
    .e_empty_n(e_empty_n),
    .e_read(grp_my_module_do_action_fu_56_e_read),
    .s_din(grp_my_module_do_action_fu_56_s_din),
    .s_full_n(s_full_n),
    .s_write(grp_my_module_do_action_fu_56_s_write)
);

assign e_read = grp_my_module_do_action_fu_56_e_read;

assign s_din = grp_my_module_do_action_fu_56_s_din;

assign s_write = grp_my_module_do_action_fu_56_s_write;

endmodule //my_module
